# Generated by Django 3.1.4 on 2020-12-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestsMessage',
        ),
    ]
