# Generated by Django 3.1.4 on 2020-12-20 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('price', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='visitors.price')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_nbr', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('room_view_direction', models.CharField(choices=[('Sea_v_nt', 'Sea_view'), ('Sea_v_st', 'Sea_view_south'), ('Garden_v_nt', 'Garden_view_north'), ('Garden_v_sth', 'Garden_view_south')], max_length=30)),
                ('nbr_peoples', models.IntegerField()),
                ('nbr_beds', models.IntegerField()),
                ('nbr_extra', models.IntegerField()),
                ('room_size', models.ManyToManyField(to='visitors.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_arival_date', models.DateField()),
                ('bk_departure_date', models.DateField()),
                ('bk_nbr_people', models.IntegerField()),
                ('bk_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.customer')),
                ('bk_rate_night', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.roomtype')),
                ('bk_room_number', models.ManyToManyField(to='visitors.Room')),
            ],
        ),
    ]
