# Generated by Django 3.1.4 on 2020-12-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_delete_guestsmessage'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(to='staff.Image'),
        ),
        migrations.CreateModel(
            name='GuestsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.customer')),
            ],
        ),
    ]
