# Generated by Django 3.1.4 on 2020-12-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20201221_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bk_arival_date',
            new_name='arival_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='bk_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='bk_departure_date',
            new_name='departure_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='bk_nbr_people',
            new_name='nbr_ppl',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='bk_rate_night',
            new_name='rate_night',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='bk_room_number',
            new_name='room_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='nbr_extra',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_size',
        ),
        migrations.AddField(
            model_name='room',
            name='room_size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='visitors.roomtype'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_view_direction',
            field=models.CharField(choices=[('Svn', 'Sea view North'), ('Svs', 'Sea view South'), ('Gvn', 'Garden view North'), ('Gvs', 'Garden view South')], max_length=30),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
