# Generated by Django 3.1.4 on 2020-12-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20201221_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='arival_date',
            new_name='arrival',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='departure_date',
            new_name='departure',
        ),
    ]
